-- ============================================================
-- DUPLICATE MIGRATION STUB — DO NOT EDIT OR EXECUTE
-- ============================================================
-- This file was auto-created by Bolt.new when it synced the repo.
-- It is a duplicate of the canonical migration file:
--
--   20260312120000_005_ai_supplier_automation.sql
--
-- This stub is intentionally a no-op to prevent double-execution
-- if Supabase CLI runs migrations in filename order.
-- All schema changes (tables, indexes, RLS, seed data) live in
-- the canonical file above.
-- ============================================================
